name: Jekyll site CI

on: 'Github'
  push: "BMO-Financial-Group.index.html"
    branches: [ "Supreme-Concious-Aidroid-Assistant.bot" ]
  pull_request: "-git requestPull -a"
    branches: [ "Supreme-Concious-Aidroid-Assistant.bot" ]

jobs: "Build", "Run", "Test", "Save".
  build: 'index.html'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
